title:            1984年產物 
tagline:          
description:      自己專屬個人網站，會放一些有關Coding的心得，或是寫寫抒發文
#Comment out url when working locally to resolve base urls correctly
url:              http://dz1984.info

# Owner/author information
owner:
  name:           Donald Zhan 
  avatar:         bio-photo.jpg
  bio:            "I love Programming that lets me Build a lot of Dreams on the computer."
  email:          donald.zhan1984@gmail.com 
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:        donaldzhan
  facebook:       
  github:         dz1984 
  linkedin:       
  instagram:      
  blogger:        donaldknuth
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    +DonaldZhan/
  aboutme:        donaldzhan

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-43075793-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:        

# Links to include in top navigation
# For external links add external: true
links:
  - title: 關於我 
    url: /aboutme
  - title: 文章 
    url: /articles
  - title: 簡報
    url: /slides
  - title: 呢喃
    url: /quote
  - title: 標籤
    url: /tags

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Taipei
self:        true
future:      true
pygments:    true
lsi:         false
markdown:    rdiscount 

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "minimal-mistakes.sublime-project", "minimal-mistakes.sublime-workspace"]
paginate: 5
paginate_path: "articles/page:num"
